### ISSUE TITLE
Template fails to compile

### ISSUE THREAD

**Issue by jmsunseri** [JaimeStill/webstack-template#1]
I thought this was a dotnet core app.  The build seems to be failing with the following error 

The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. ...

why is it referencing 4.6.2?

**Comment by JaimeStill** [comment]
It's an ASP.NET Core app targeting .NET Framework 4.6.2. The reason is because I still rely on the Active Directory and Powershell assemblies at work. To get it to target .NET Core, make the following modifications to the generated `.csproj` file:

``` xml
<PropertyGroup>
    <TargetFramework>net462</TargetFramework> <!-- change net462 to netcoreapp2.0 -->
    <RuntimeIdentifiers>win10-x64;win7-x64</RuntimeIdentifiers> <!-- remove this -->
```  

To see a sample of where I've modified myself, refer to this [`.csproj`](https://github.com/JaimeStill/arma-demo/blob/master/arma-demo.web/arma-demo.web.csproj) file.

**Comment by JaimeStill** [comment]
Also note, in the linked `.csproj` file above, the ASP.NET Core dependencies can be simplified with the `Microsoft.AspNetCore.All` NuGet package.
